name: Auto Review and Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # - name: Berikan review otomatis
      #   if: github.actor == 'msalmanrafadhlih' || github.actor == 'mochsalman'
      #   uses: peter-evans/review-pull-request@v7
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     pull-request-number: ${{ github.event.pull_request.number }}
      #     event: APPROVE
      #     body: |
      #       ✅ PR ini telah direview secara otomatis. Jika tidak ada perubahan lain, PR ini akan di-approve dan di-merge segera.

      - name: Approve PR jika dari contributor yang diizinkan
        if: github.actor == 'msalmanrafadhlih' || github.actor == 'mochsalman'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Aktifkan auto-merge
        if: github.actor == 'msalmanrafadhlih' || github.actor == 'mochsalman'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
