name: ReadMe Stats Updater

on:
  workflow_run:
    workflows: ["Main ReadMe Updater"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  UpdateStatsTemplate:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.USER_TOKEN }}
          template: ./README.md
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "[Automatic] Updated Stats ReadMe.md 
          
          Co-authored-by: ${{ secrets.CO_USERNAME }} <${{ secrets.CO_AUTHOR }}@gmail.com>"
          git push --all -f https://${{ secrets.MY_PAT }}@github.com/${GITHUB_REPOSITORY}.git
          fi
